name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v12
      - run: nix build --extra-experimental-features
